## 1. Vector

In [1]:
## Thư viện
import numpy as np
import pandas as pd
import scipy.spatial.distance as dist 
import warnings
warnings.filterwarnings('ignore')
from numpy.linalg import norm

## Tạo Vectors
. Tạo vector v1(1,3,5,7)
. Tạo vector v2(2,4,6,8)

In [2]:
v1 = np.array([1,3,5,7])
v2 = np.array([2,4,6,8])

print(v1)
print(v2)

[1 3 5 7]
[2 4 6 8]


In [3]:
## Tạo vecotr với các giá trị được phát sinh theo quy luật
v = np.array(np.arange(10))
print(v)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
## Tạo vector với các phần tử = 0.0
v = np.zeros(5)
print(v)

[0. 0. 0. 0. 0.]


In [5]:
## Tạo vector với các phần tử = 1.0
v = np.ones(5)
print(v)

[1. 1. 1. 1. 1.]


In [6]:
## Tạo vector với các giá trị được phát sinh một cách ngẫu nhiên
v = np.random.random(4)
print(v)

[0.80110013 0.87346741 0.95751524 0.08249182]


In [7]:
## Tạo vector với các giá trị số nguyên ngẫu nhiên
v = np.random.randint(0,11,4) # tạo 4 phần tử từ 0 => 10
print(v)

[ 8  5  3 10]


## 2. Tích vô hướng 2 vectors

In [8]:
## Tính tích vô hướng bằng .dot()
v1.dot(v2), v2.dot(v1) #Tính giao hoán

(100, 100)

In [9]:
## Tích vô hướng bằng toán tử @
v1 @ v2, v2 @ v1

(100, 100)

## 3. bang_diem.csv

In [10]:
# Tập tin bang_diem.csv lưu trữ điểm thi của các thí sinh
# Liệt kê danh sách N thí sinh trúng tuyển (Giá trị N được nhập từ bàn phím): diem_1, diem_2 được tính
#hệ số 2 và diem_3 được tính hệ số 1.
# Cho biết thí sinh đạt thủ khoa

In [11]:
# Mở tập tin bang_diem.csv
df = pd.read_csv('Data/bang_diem.csv')
print('Danh sách thí sinh:\n', df.to_string(index = False))

Danh sách thí sinh:
  maso                ho    ten  diem_1  diem_2  diem_3
    1  Huỳnh Thùy Thiên     An     8.0     2.0     7.0
    2          Bùi Tuấn    Anh     8.0     8.4     6.4
    3           Hồ Tuấn    Anh     7.0     7.6     7.8
    4           Ngô Kim    Anh     8.0     7.0     2.5
    5       Nguyễn Nhật    Anh     8.0     4.4     3.8
    6  Trần Ngọc Phương    Anh     8.0     6.4     7.2
    7       Nguyễn Minh   Châu     7.0     8.0     8.4
    8  Trịnh Nguyễn Yến   Dung     8.0     2.8     6.8
    9         Huỳnh Vạn    Gia     6.0     5.2     5.0
   10   Nông Đặng Quỳnh  Giang     8.0     6.4     8.9
   11         Đặng Minh    Hào     8.0     7.6     9.2
   12          Ngô Quốc    Hào     7.0     5.0     5.4
   13   Phạm Đoàn Thanh   Hiền     8.0     9.6     8.7
   14       Nguyễn Nhật  Hoàng     8.0     5.6     7.4
   15      Nguyễn Thanh  Hương     8.0     4.4     7.2
   16           Ngô Gia    Huy     8.0     9.0     9.2
   17         Trương Mĩ  Khanh     7.0     3

In [12]:
# Xét tuyển
heso = np.array([2,2,1])
N = eval(input(f"\n Số chỉ tiêu tuyển sinh (n < {len(df)}) = "))

In [13]:
## Tính tổng điểm theo hệ số
df['tong_diem'] = df[['diem_1', 'diem_2', 'diem_3']] @ heso # tích vô hướng
print('*** Bảng Điểm:\n',df)

*** Bảng Điểm:
     maso                 ho     ten  diem_1  diem_2  diem_3  tong_diem
0      1   Huỳnh Thùy Thiên      An     8.0     2.0     7.0       27.0
1      2           Bùi Tuấn     Anh     8.0     8.4     6.4       39.2
2      3            Hồ Tuấn     Anh     7.0     7.6     7.8       37.0
3      4            Ngô Kim     Anh     8.0     7.0     2.5       32.5
4      5        Nguyễn Nhật     Anh     8.0     4.4     3.8       28.6
5      6   Trần Ngọc Phương     Anh     8.0     6.4     7.2       36.0
6      7        Nguyễn Minh    Châu     7.0     8.0     8.4       38.4
7      8   Trịnh Nguyễn Yến    Dung     8.0     2.8     6.8       28.4
8      9          Huỳnh Vạn     Gia     6.0     5.2     5.0       27.4
9     10    Nông Đặng Quỳnh   Giang     8.0     6.4     8.9       37.7
10    11          Đặng Minh     Hào     8.0     7.6     9.2       40.4
11    12           Ngô Quốc     Hào     7.0     5.0     5.4       29.4
12    13    Phạm Đoàn Thanh    Hiền     8.0     9.6     8.7  

In [14]:
## Xác định điểm chuẩn trúng tuyển
df.sort_values(by = ['tong_diem'], ascending=False, ignore_index=True, inplace=True)
diem_chuan = df[N-1:N].tong_diem.values[0]

## Danh sách thí sinh trúng tuyển
result = df[df.tong_diem >= diem_chuan].sort_values(by = ['maso'])
print(f"** Danh sách {len(result)} thí sinh trúng tuyển (điểm chuẩn = {diem_chuan}):")
print(result.to_string(index=False))

** Danh sách 30 thí sinh trúng tuyển (điểm chuẩn = 26.8):
 maso                ho    ten  diem_1  diem_2  diem_3  tong_diem
    1  Huỳnh Thùy Thiên     An     8.0     2.0     7.0       27.0
    2          Bùi Tuấn    Anh     8.0     8.4     6.4       39.2
    3           Hồ Tuấn    Anh     7.0     7.6     7.8       37.0
    4           Ngô Kim    Anh     8.0     7.0     2.5       32.5
    5       Nguyễn Nhật    Anh     8.0     4.4     3.8       28.6
    6  Trần Ngọc Phương    Anh     8.0     6.4     7.2       36.0
    7       Nguyễn Minh   Châu     7.0     8.0     8.4       38.4
    8  Trịnh Nguyễn Yến   Dung     8.0     2.8     6.8       28.4
    9         Huỳnh Vạn    Gia     6.0     5.2     5.0       27.4
   10   Nông Đặng Quỳnh  Giang     8.0     6.4     8.9       37.7
   11         Đặng Minh    Hào     8.0     7.6     9.2       40.4
   12          Ngô Quốc    Hào     7.0     5.0     5.4       29.4
   13   Phạm Đoàn Thanh   Hiền     8.0     9.6     8.7       43.9
   14       Nguyễn

In [16]:
## Thí sinh đạt thủ khoa
print(df[df.tong_diem == max(df.tong_diem)].to_string(index=False))

 maso              ho  ten  diem_1  diem_2  diem_3  tong_diem
   13 Phạm Đoàn Thanh Hiền     8.0     9.6     8.7       43.9


## 4. Tính NORMS của Vectors

In [17]:
## Tạo vector v(1,3,-4,5,7,9,-6)
## Tính Norms L1, L2 và Lmax của vector v

In [18]:
v = np.array([1,3,-4,5,7,9,-6])

In [19]:
# L1 norm
print("L1 norm:", norm(v,1))

L1 norm: 35.0


In [20]:
## L2 norm
print("L2 norm: ", norm(v,2), norm(v))

L2 norm:  14.730919862656235 14.730919862656235


In [21]:
## Max norm
print('Max norm: ', norm(v, np.inf))

Max norm:  9.0


In [22]:
# Đại lượng khoảng cách (từ gốc tọa độ đến Đỉnh)
O = np.zeros(7) # gốc tọa độ

## Các khoảng cách
print('Manhattan distance = ', dist.cityblock(O,v))
print('Euclidean distance = ', dist.euclidean(O,v))
print('Chebyshev distance = ', dist.chebyshev(O,v))

Manhattan distance =  35.0
Euclidean distance =  14.730919862656235
Chebyshev distance =  9.0
