## Ma Trận

In [1]:
import numpy as np 
import pandas as pd 
import warnings
warnings.filterwarnings('ignore')
from numpy.linalg import norm, inv, det

## 1. Nhân ma trận

In [2]:
## Tạo các ma trận A và B
A = np.array([[2, 5, 4], [3, 6, 1]])
B = np.array([[3,2],[1,4],[5,7]])

In [3]:
## Nhân các ma trận A và B
print('Ma trận A:\n', A)
print('Ma trận B:\n', B)
print('Ma trận A.B:\n', A.dot(B))
print('Ma trận A.B:\n', A @ B)

Ma trận A:
 [[2 5 4]
 [3 6 1]]
Ma trận B:
 [[3 2]
 [1 4]
 [5 7]]
Ma trận A.B:
 [[31 52]
 [20 37]]
Ma trận A.B:
 [[31 52]
 [20 37]]


## 2. Nhân ma trận với vector

In [4]:
A = np.array([[2,4,6], [1,3,5], [4,2,1]])
v = np.array([1,2,3])
print('Ma trận A:\n', A)
print('Vector v:\n', v)
print('Vector A.v:\n', A.dot(v), A @ v)

Ma trận A:
 [[2 4 6]
 [1 3 5]
 [4 2 1]]
Vector v:
 [1 2 3]
Vector A.v:
 [28 22 11] [28 22 11]


## 3. Tính L2 norm của các vectors (dòng) trong tập tin

In [5]:
# đọc tập tin iris.csv vào dataframe df
# Từ df, hãy tạo ma trận A với các thuộc tính 'sepal_length', 'sepal_width', 'petal_length', 'petal_width'
# Tính L2 norm cho mỗi vector dòng của ma trận A

In [6]:
df = pd.read_csv('Data/iris.csv')
A = np.array(df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']])

In [7]:
# Kích thước của ma trận A
A.shape

(150, 4)

In [8]:
# 5 dòng đầu tiên
A[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [9]:
# 5 dòng cuối cùng
A[-5:]

array([[6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [10]:
## tính L2 norm của mỗi dòng A[i] và lưu kết quả trong norms[]
norms = []
for i in range(A.shape[0]):
    norms.append(norm(A[i, :]))

result = np.array(norms)
print(result[:5])

[6.34507683 5.91692488 5.83609458 5.7497826  6.32139225]


## 4. Tìm ma trận chuyển vị của A = [[1,2,3],[4,5,6]]

In [11]:
# Ma trận chuyển vị
A = np.array([[1,2,3],[4,5,6]])
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 5 Tìm ma trận nghịch đảo của A

In [12]:
A = np.array([[1,2,3],[4,5,6],[3,2,4]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 4]])

In [13]:
# Kiểm tra định thức khác 0
det(A)

-9.000000000000002

In [14]:
## ma trận nghịch đảo
inv(A)

array([[-0.88888889,  0.22222222,  0.33333333],
       [-0.22222222,  0.55555556, -0.66666667],
       [ 0.77777778, -0.44444444,  0.33333333]])

In [15]:
## Kiểm chứng ma trận nghịch đảo # A.A_1 = I
print(np.rint(A @ inv(A)).astype(int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [16]:
## Ma trận suy biến (singular matrix): định thức = 0
A = np.array([[1,2], [2,4]])
print(f"Định thức của A = {det(A)}")

print(inv(A)) # Báo lỗi sai

Định thức của A = 0.0


LinAlgError: Singular matrix