# ** Ma trận thưa**

---
## **Phương pháp CSR (Compressed Sparse Row)**
   Giả sử ma trận A có **m** dòng và A có **p** phần từ <> 0
   
   ** Tạo 3 arrays có kích thước khác nhau:

      1) data[p]      : chứa các giá trị <> 0
      2) indices[p]   : chứa các chỉ số CỘT của các phần tử <> 0
      3) indptr[m + 1]: chứa một dãy số tăng (không đều) từ 0 cho đến p
                        là VỊ TRÍ BẮT ĐẦU rút trích trong data[] cho mỗi dòng
         idxptr = (start_r(0), start_r(1), start_r(2), ..., start_r(m-1), p)
         
         Lưu ý: indptr[0]     = start_r(0) = 0
                idxptr[m + 1] = p
                
         VD: idxptr = (0, 2, 5, 7, 9, 12)
         Gọi P(i) là tập các giá trị <> 0 của dòng i, rút trích từ trong data[]
            P(0) = { data[0], data[1] }
            P(1) = { data[2], data[3], data[4] }
            P(2) = { data[5], data[6] }
            P(3) = { data[7], data[8] }
            P(4) = { data[9], data[10], data[11] }
---

---
## **Yêu cầu 1: Lưu trữ ma trận thưa dưới dạng CSR**
---

In [5]:
import numpy        as np
import scipy.sparse as sparse
import warnings
warnings.filterwarnings('ignore')

A = np.array([[8, 0, 0, 6, 0, 0],
              [0, 0, 9, 0, 0, 4],
              [0, 0, 0, 3, 0, 0]])

In [6]:
# Chuyển ma trận sang CSR format
csr = sparse.csr_matrix(A)

In [7]:
## DATA array: [8, 6, 9, 4, 3]
print('DATA array: ', csr.data)

DATA array:  [8 6 9 4 3]


In [9]:
## INDICES Array: [0, 3, 2, 5, 3]
print('INDICES array: ', csr.indices)

INDICES array:  [0 3 2 5 3]


In [10]:
## POINTER array: [0 2 4 5]
print('POINTER array: ', csr.indptr)

POINTER array:  [0 2 4 5]


In [11]:
## Lưu ý:
print('Lưu ý: Nếu không chỉ định các properties ---> LIL format:')
print(csr)

Lưu ý: Nếu không chỉ định các properties ---> LIL format:
  (0, 0)	8
  (0, 3)	6
  (1, 2)	9
  (1, 5)	4
  (2, 3)	3


---
## **Yêu cầu 2: Tái tạo ma trận thưa từ CSR format**
---

In [12]:
## Input: 3 arrays
d   = np.array([8, 6, 9, 4, 3])
ind = np.array([0, 3, 2, 5, 3])
ptr = np.array([0, 2, 4, 5])

## Tái tạo ma trận thưa
mtx = sparse.csr_matrix((d, ind, ptr))

print('\nTái tạo ma trận từ CSR format (default shape):\n', mtx.todense())


Tái tạo ma trận từ CSR format (default shape):
 [[8 0 0 6 0 0]
 [0 0 9 0 0 4]
 [0 0 0 3 0 0]]


In [13]:
mtx = sparse.csr_matrix((d, ind, ptr), shape = (3, 10))
print('\nTái tạo ma trận từ CSR format (explicit shape):\n', mtx.todense())


Tái tạo ma trận từ CSR format (explicit shape):
 [[8 0 0 6 0 0 0 0 0 0]
 [0 0 9 0 0 4 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]]
